### ISSUE TITLE
Failure to Make - on 4.12 Kali

### ISSUE THREAD

**Issue by clayday27** [jurobystricky/Netgear-A6210#80]
Hello,

Failed to make file

/var/lib/dkms/Netgear-A6210/1.0/build/os/linux/../../os/linux/cfg80211/cfg80211.c:2385:25: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .change_virtual_intf = CFG80211_OpsVirtualInfChg,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/Netgear-A6210/1.0/build/os/linux/../../os/linux/cfg80211/cfg80211.c:2385:25: note: (near initialization for 'CFG80211_Ops.change_virtual_intf')
/var/lib/dkms/Netgear-A6210/1.0/build/os/linux/../../os/linux/cfg80211/cfg80211.c:2386:22: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .add_virtual_intf = CFG80211_OpsVirtualInfAdd,
                      ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/Netgear-A6210/1.0/build/os/linux/../../os/linux/cfg80211/cfg80211.c:2386:22: note: (near initialization for 'CFG80211_Ops.add_virtual_intf')
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.12.0-kali2-common/scripts/Makefile.build:307: recipe for target '/var/lib/dkms/Netgear-A6210/1.0/build/os/linux/../../os/linux/cfg80211/cfg80211.o' failed
make[4]: *** [/var/lib/dkms/Netgear-A6210/1.0/build/os/linux/../../os/linux/cfg80211/cfg80211.o] Error 1
/usr/src/linux-headers-4.12.0-kali2-common/Makefile:1532: recipe for target '_module_/var/lib/dkms/Netgear-A6210/1.0/build/os/linux' failed
make[3]: *** [_module_/var/lib/dkms/Netgear-A6210/1.0/build/os/linux] Error 2

**Comment by genodeftest** [comment]
Hi clayday27,
can you please put your code into code blocks? That would increase readability a lot.

#77 has some changes which should make the A6210 kernel module build with kernel 4.12. Please try that change.
