### ISSUE TITLE
Linux Mint 19 make fails

### ISSUE THREAD

**Issue by taladan** [jurobystricky/Netgear-A6210#125]
OS:
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara

Issue:

```
  CC [M]  /home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux/../../os/linux/rt_linux.o
/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux/../../os/linux/rt_linux.c: In function ‘__RTMP_OS_Init_Timer’:
/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux/../../os/linux/rt_linux.c:107:3: error: implicit declaration of function ‘init_timer’; did you mean ‘init_timers’? [-Werror=implicit-function-declaration]
   init_timer(pTimer);
   ^~~~~~~~~~
   init_timers
/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux/../../os/linux/rt_linux.c:108:9: error: ‘struct timer_list’ has no member named ‘data’
   pTimer->data = (unsigned long)data;
         ^~
/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux/../../os/linux/rt_linux.c:109:20: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
   pTimer->function = function;
                    ^
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux/../../os/linux/rt_linux.o' failed
make[2]: *** [/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux/../../os/linux/rt_linux.o] Error 1
Makefile:1551: recipe for target '_module_/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux' failed
make[1]: *** [_module_/home/taladan/Downloads/Netgear-A6210-port-to-4.14/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-39-generic'
Makefile:59: recipe for target 'debug' failed
make: *** [debug] Error 2

```
Any help would be much appreciated - my old adapter is dying a crushing death and I spent 40 bucks I couldn't afford (stupidly forgetting to check compatability first) and I'd like to avoid having to refund and get a different one if I can make this one work.

**Comment by PascalSalesch** [comment]
try this port: https://github.com/kaduke/Netgear-A6210/tree/port-to-4.15/

**Comment by PhilipDeegan** [comment]
@PascalSalesch segfaults @ modprobe >_<

**Comment by imchao9** [comment]
not work on 4.15.0-45 but work on 4.15.0-20
