### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Sonja-py** [jurobystricky/Netgear-A6210#74]
I'm kinda new to all this stuff so I have no idea what's wrong.
After I run `make` I get this:

`cp -f os/linux/Makefile.6 /home/dir/Netgear-A6210/os/linux/Makefile`
`make -C /lib/modules/4.11.9-1-ARCH/build DBGFLAGS=-DDBG SUBDIRS=/home/dir/Netgear-A6210/os/linux modules`
`make[1]: Entering directory '/usr/lib/modules/4.11.9-1-ARCH/build'`
  `CC [M]  /home/dir/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211_inf.o`
`/home/dir/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211_inf.c: In function ‘RTMP_CFG80211_VirtualIF_Init’:`
`/home/dir/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211_inf.c:552:13: error: ‘struct net_device’ has no member named ‘destructor’; did you mean ‘priv_destructor’?`
`         new_dev_p->destructor = free_netdev;`
`                              ^~~~~~~~~~`
`                              priv_destructor`
`make[2]: *** [scripts/Makefile.build:295: /home/dir/Netgear-A6210/os/linux/../../os/linux/cfg80211/cfg80211_inf.o] Error 1`
`make[1]: *** [Makefile:1492: _module_/home/dir/Netgear-A6210/os/linux] Error 2`
`make[1]: Leaving directory '/usr/lib/modules/4.11.9-1-ARCH/build'`
`make: *** [Makefile:64: debug] Error 2`

**Comment by kraftie** [comment]
Can confirm. Happened when upgrading from Kernel 4.11.0x to 4.11.10. Just do as instructed and replace "destructor" by "priv_destructor". Works perfectly after.
